services:
  # Backend API Only
  - type: web
    name: lms-backend
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install fastapi uvicorn pydantic python-multipart python-dotenv
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: PORT
        value: 8000
