services:
  # Backend API
  - type: web
    name: lms-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: PORT
        value: 8000

  # Frontend Static Site
  - type: web
    name: lms-frontend
    env: static
    buildCommand: echo "Frontend ready"
    staticPublishPath: ./frontend
    envVars:
      - key: API_BASE_URL
        value: https://lms-backend.onrender.com
